"""
Iterate the link got from the json file generated by scrape_amazon_review.py to get all posts by each customer
"""
import itertools
import json
import requests
import time
from bs4 import BeautifulSoup

from requests_html import HTMLSession

from scrape_amazon_review import Reviews


def read_json(json_address):
    with open(json_address, 'r') as f:
        # Load the contents of the file into a Python object
        data = json.load(f)
    flattened_list = list(itertools.chain(*data))
    return flattened_list


def get_length(review_list):
    print(len(review_list))



if __name__ == '__main__':
    json_address = "B094PS5RZQ-reviews.json"
    review_list = read_json(json_address)
    get_length(review_list)

